spring:
  application:
    name: collector
  rabbitmq:
    publisher-confirm-type: correlated
    publisher-returns: true

airport:
  collection:
    enabled: ${AIRPORT_COLLECTION_ENABLED:false}
    fixed-delay: ${AIRPORT_COLLECTION_FIXED_DELAY:PT5M}
    initial-delay: ${AIRPORT_COLLECTION_INITIAL_DELAY:PT1S}
  api:
    num-of-rows: ${AIRPORT_API_NUM_OF_ROWS:1000}
    arrival-status:
      url: ${AIRPORT_ARRIVAL_STATUS_API_URL:}
      key: ${AIRPORT_ARRIVAL_STATUS_API_KEY:}
    passenger-forecast:
      url: ${AIRPORT_PASSENGER_FORECAST_API_URL:}
      key: ${AIRPORT_PASSENGER_FORECAST_API_KEY:}
    railroad:
      url: ${AIRPORT_RAILROAD_API_URL:}
      key: ${AIRPORT_RAILROAD_API_KEY:}
      train-class: ${AIRPORT_RAILROAD_TRAIN_CLASS:}
      station-code: ${AIRPORT_RAILROAD_STATION_CODE:}

inference:
  consumer:
    auto-startup: ${INFERENCE_CONSUMER_AUTO_STARTUP:true}

congestion:
  calculation:
    enabled: ${CONGESTION_CALCULATION_ENABLED:false}
    fixed-rate: ${CONGESTION_CALCULATION_FIXED_RATE:PT10S}
    initial-delay: ${CONGESTION_CALCULATION_INITIAL_DELAY:PT10S}
    api-max-age: ${CONGESTION_API_MAX_AGE:PT10M}
    model-max-age: ${CONGESTION_MODEL_MAX_AGE:PT10S}
  moving-walkway:
    enabled: ${CONGESTION_MOVING_WALKWAY_ENABLED:false}
    sensor-space-id: ${CONGESTION_SENSOR_SPACE_ID:}
    carriers-per-passenger: ${CONGESTION_CARRIERS_PER_PASSENGER:}
    route-b:
      split: ${CONGESTION_ROUTE_B_SPLIT:}
      retention-length-seconds: ${CONGESTION_ROUTE_B_RETENTION_LENGTH_SECONDS:}
      walkway-arrival-offset-seconds: ${CONGESTION_ROUTE_B_WALKWAY_ARRIVAL_OFFSET_SECONDS:}
      available-passage-time-seconds: ${CONGESTION_ROUTE_B_AVAILABLE_PASSAGE_TIME_SECONDS:}
      congested-passage-time-seconds: ${CONGESTION_ROUTE_B_CONGESTED_PASSAGE_TIME_SECONDS:}
      remaining-travel-time-seconds: ${CONGESTION_ROUTE_B_REMAINING_TRAVEL_TIME_SECONDS:}
    route-c:
      split: ${CONGESTION_ROUTE_C_SPLIT:}
      retention-length-seconds: ${CONGESTION_ROUTE_C_RETENTION_LENGTH_SECONDS:}
      walkway-arrival-offset-seconds: ${CONGESTION_ROUTE_C_WALKWAY_ARRIVAL_OFFSET_SECONDS:}
      available-passage-time-seconds: ${CONGESTION_ROUTE_C_AVAILABLE_PASSAGE_TIME_SECONDS:}
      congested-passage-time-seconds: ${CONGESTION_ROUTE_C_CONGESTED_PASSAGE_TIME_SECONDS:}
      remaining-travel-time-seconds: ${CONGESTION_ROUTE_C_REMAINING_TRAVEL_TIME_SECONDS:}
  publisher:
    confirm-timeout: ${CONGESTION_PUBLISH_CONFIRM_TIMEOUT:PT2S}
