global:
  scrape_interval: 15s

scrape_configs:
  - job_name: drrk-app-main
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app-main:8080

  - job_name: drrk-app-collector
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - app-collector:8081
